systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard2\rs0\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard2\rs0\data

processManagement:
  windowsService:
    serviceName: MongoShard2_0
    displayName: Mongo Shard 2 Node 0

net:
  bindIp: localhost
  port: 27110

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS2

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
