systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Config\cfg2\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Config\cfg2\data

processManagement:
  windowsService:
    serviceName: MongoConfig2
    displayName: Mongo Config Server 2

net:
  bindIp: localhost
  port: 27021

sharding:
  clusterRole: configsvr

replication:
  replSetName: ConfigRS

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
