systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Config\cfg0\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Config\cfg0\data

processManagement:
  windowsService:
    serviceName: MongoConfig0
    displayName: Mongo Config Server 0

net:
  bindIp: localhost
  port: 27019

sharding:
  clusterRole: configsvr

replication:
  replSetName: ConfigRS

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
