systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard4\rs2\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard4\rs2\data

processManagement:
  windowsService:
    serviceName: MongoShard4_2
    displayName: Mongo Shard 4 Node 2

net:
  bindIp: localhost
  port: 27132

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS4

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
