systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard4\rs1\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard4\rs1\data

processManagement:
  windowsService:
    serviceName: MongoShard4_1
    displayName: Mongo Shard 4 Node 1

net:
  bindIp: localhost
  port: 27131

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS4

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
