systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard2\rs2\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard2\rs2\data

processManagement:
  windowsService:
    serviceName: MongoShard2_2
    displayName: Mongo Shard 2 Node 2

net:
  bindIp: localhost
  port: 27112

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS2

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
