systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard3\rs1\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard3\rs1\data

processManagement:
  windowsService:
    serviceName: MongoShard3_1
    displayName: Mongo Shard 3 Node 1

net:
  bindIp: localhost
  port: 27121

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS3

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
