systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard4\rs0\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard4\rs0\data

processManagement:
  windowsService:
    serviceName: MongoShard4_0
    displayName: Mongo Shard 4 Node 0

net:
  bindIp: localhost
  port: 27130

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS4

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
