systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Config\cfg1\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Config\cfg1\data

processManagement:
  windowsService:
    serviceName: MongoConfig1
    displayName: Mongo Config Server 1

net:
  bindIp: localhost
  port: 27020

sharding:
  clusterRole: configsvr

replication:
  replSetName: ConfigRS

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
