systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard3\rs0\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard3\rs0\data

processManagement:
  windowsService:
    serviceName: MongoShard3_0
    displayName: Mongo Shard 3 Node 0

net:
  bindIp: localhost
  port: 27120

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS3

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
