systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard1\rs1\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard1\rs1\data

processManagement:
  windowsService:
    serviceName: MongoShard1_1
    displayName: Mongo Shard 1 Node 1

net:
  bindIp: localhost
  port: 27101

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS1

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
