systemLog:
  destination: file
  path: C:\MONGODB\Cluster\Shard1\rs0\log\mongod.log
  logAppend: true

storage:
  dbPath: C:\MONGODB\Cluster\Shard1\rs0\data

processManagement:
  windowsService:
    serviceName: MongoShard1_0
    displayName: Mongo Shard 1 Node 0

net:
  bindIp: localhost
  port: 27100

sharding:
  clusterRole: shardsvr

replication:
  replSetName: ShardRS1

security:
  keyFile: C:\MONGODB\Cluster\KeyFile\mongodb-keyfile
